"""sprint4_add_buildings

Revision ID: 2503d771d871
Revises: 57d4f014fc64
Create Date: 2026-07-21 23:46:57.272125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2503d771d871'
down_revision: Union[str, Sequence[str], None] = '57d4f014fc64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('datacenter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('number_of_floors', sa.Integer(), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('power_capacity_kw', sa.Float(), nullable=True),
    sa.Column('cooling_capacity_kw', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['datacenter_id'], ['datacenters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datacenter_id', 'code', name='uq_building_datacenter_code'),
    sa.UniqueConstraint('datacenter_id', 'name', name='uq_building_datacenter_name')
    )
    op.create_index('ix_buildings_company_id', 'buildings', ['company_id'], unique=False)
    op.create_index('ix_buildings_datacenter_id', 'buildings', ['datacenter_id'], unique=False)
    op.create_index('ix_buildings_status', 'buildings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_buildings_status', table_name='buildings')
    op.drop_index('ix_buildings_datacenter_id', table_name='buildings')
    op.drop_index('ix_buildings_company_id', table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
