"""add_monitoring_tables

Revision ID: 2712cd0d42fc
Revises: 61d7211ae693
Create Date: 2026-07-22 02:21:34.166135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2712cd0d42fc'
down_revision: Union[str, Sequence[str], None] = '61d7211ae693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_definitions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metric_key', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_key')
    )
    op.create_index('ix_metric_definitions_category', 'metric_definitions', ['category'], unique=False)
    op.create_index('ix_metric_definitions_metric_key', 'metric_definitions', ['metric_key'], unique=True)
    op.create_index('ix_metric_definitions_name', 'metric_definitions', ['name'], unique=False)
    op.create_table('health_checks',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_checks_checked_at', 'health_checks', ['checked_at'], unique=False)
    op.create_index('ix_health_checks_company_id', 'health_checks', ['company_id'], unique=False)
    op.create_index('ix_health_checks_device_checked', 'health_checks', ['device_id', 'checked_at'], unique=False)
    op.create_index('ix_health_checks_device_id', 'health_checks', ['device_id'], unique=False)
    op.create_index('ix_health_checks_status', 'health_checks', ['status'], unique=False)
    op.create_table('monitoring_targets',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('collector_type', sa.String(length=20), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_monitoring_targets_collector_type', 'monitoring_targets', ['collector_type'], unique=False)
    op.create_index('ix_monitoring_targets_company_id', 'monitoring_targets', ['company_id'], unique=False)
    op.create_index('ix_monitoring_targets_device_id', 'monitoring_targets', ['device_id'], unique=False)
    op.create_index('ix_monitoring_targets_enabled', 'monitoring_targets', ['enabled'], unique=False)
    op.create_index('ix_monitoring_targets_status', 'monitoring_targets', ['status'], unique=False)
    op.create_table('metric_data',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('metric_definition_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definitions.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['monitoring_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metric_data_company_device_def', 'metric_data', ['company_id', 'device_id', 'metric_definition_id'], unique=False)
    op.create_index('ix_metric_data_company_id', 'metric_data', ['company_id'], unique=False)
    op.create_index('ix_metric_data_device_id', 'metric_data', ['device_id'], unique=False)
    op.create_index('ix_metric_data_device_timestamp', 'metric_data', ['device_id', 'timestamp'], unique=False)
    op.create_index('ix_metric_data_metric_definition_id', 'metric_data', ['metric_definition_id'], unique=False)
    op.create_index('ix_metric_data_target_id', 'metric_data', ['target_id'], unique=False)
    op.create_index('ix_metric_data_timestamp', 'metric_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metric_data_timestamp', table_name='metric_data')
    op.drop_index('ix_metric_data_target_id', table_name='metric_data')
    op.drop_index('ix_metric_data_metric_definition_id', table_name='metric_data')
    op.drop_index('ix_metric_data_device_timestamp', table_name='metric_data')
    op.drop_index('ix_metric_data_device_id', table_name='metric_data')
    op.drop_index('ix_metric_data_company_id', table_name='metric_data')
    op.drop_index('ix_metric_data_company_device_def', table_name='metric_data')
    op.drop_table('metric_data')
    op.drop_index('ix_monitoring_targets_status', table_name='monitoring_targets')
    op.drop_index('ix_monitoring_targets_enabled', table_name='monitoring_targets')
    op.drop_index('ix_monitoring_targets_device_id', table_name='monitoring_targets')
    op.drop_index('ix_monitoring_targets_company_id', table_name='monitoring_targets')
    op.drop_index('ix_monitoring_targets_collector_type', table_name='monitoring_targets')
    op.drop_table('monitoring_targets')
    op.drop_index('ix_health_checks_status', table_name='health_checks')
    op.drop_index('ix_health_checks_device_id', table_name='health_checks')
    op.drop_index('ix_health_checks_device_checked', table_name='health_checks')
    op.drop_index('ix_health_checks_company_id', table_name='health_checks')
    op.drop_index('ix_health_checks_checked_at', table_name='health_checks')
    op.drop_table('health_checks')
    op.drop_index('ix_metric_definitions_name', table_name='metric_definitions')
    op.drop_index('ix_metric_definitions_metric_key', table_name='metric_definitions')
    op.drop_index('ix_metric_definitions_category', table_name='metric_definitions')
    op.drop_table('metric_definitions')
    # ### end Alembic commands ###
