"""sprint8_add_devices

Revision ID: 51af639ebb91
Revises: b59766de5056
Create Date: 2026-07-22 01:01:08.643422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51af639ebb91'
down_revision: Union[str, Sequence[str], None] = 'b59766de5056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('rack_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('asset_tag', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rack_unit_start', sa.Integer(), nullable=True),
    sa.Column('rack_unit_height', sa.Integer(), nullable=False),
    sa.Column('front_or_rear', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('management_ip', sa.String(length=45), nullable=True),
    sa.Column('operating_system', sa.String(length=255), nullable=True),
    sa.Column('cpu', sa.String(length=255), nullable=True),
    sa.Column('memory_gb', sa.Integer(), nullable=True),
    sa.Column('storage_gb', sa.Integer(), nullable=True),
    sa.Column('power_consumption_watt', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.String(length=10), nullable=True),
    sa.Column('warranty_end_date', sa.String(length=10), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_tag'),
    sa.UniqueConstraint('company_id', 'name', name='uq_device_company_name'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index('ix_devices_asset_tag', 'devices', ['asset_tag'], unique=True)
    op.create_index('ix_devices_company_id', 'devices', ['company_id'], unique=False)
    op.create_index('ix_devices_device_type', 'devices', ['device_type'], unique=False)
    op.create_index('ix_devices_rack_id', 'devices', ['rack_id'], unique=False)
    op.create_index('ix_devices_serial_number', 'devices', ['serial_number'], unique=True)
    op.create_index('ix_devices_status', 'devices', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_status', table_name='devices')
    op.drop_index('ix_devices_serial_number', table_name='devices')
    op.drop_index('ix_devices_rack_id', table_name='devices')
    op.drop_index('ix_devices_device_type', table_name='devices')
    op.drop_index('ix_devices_company_id', table_name='devices')
    op.drop_index('ix_devices_asset_tag', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
