"""create datacenters table

Revision ID: 57d4f014fc64
Revises: 6ef9d91eabb0
Create Date: 2026-07-21 23:23:41.936346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d4f014fc64'
down_revision: Union[str, Sequence[str], None] = '6ef9d91eabb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datacenters',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_datacenter_company_code'),
    sa.UniqueConstraint('company_id', 'name', name='uq_datacenter_company_name')
    )
    op.create_index('ix_datacenters_city', 'datacenters', ['city'], unique=False)
    op.create_index('ix_datacenters_company_id', 'datacenters', ['company_id'], unique=False)
    op.create_index('ix_datacenters_country', 'datacenters', ['country'], unique=False)
    op.create_index('ix_datacenters_status', 'datacenters', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_datacenters_status', table_name='datacenters')
    op.drop_index('ix_datacenters_country', table_name='datacenters')
    op.drop_index('ix_datacenters_company_id', table_name='datacenters')
    op.drop_index('ix_datacenters_city', table_name='datacenters')
    op.drop_table('datacenters')
    # ### end Alembic commands ###
