"""add_network_topology_tables

Revision ID: 61d7211ae693
Revises: c39e59cdb8ff
Create Date: 2026-07-22 02:03:47.029095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d7211ae693'
down_revision: Union[str, Sequence[str], None] = 'c39e59cdb8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vlans',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('datacenter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['datacenter_id'], ['datacenters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'vlan_id', name='uq_vlan_company_vlan_id')
    )
    op.create_index('ix_vlans_company_id', 'vlans', ['company_id'], unique=False)
    op.create_index('ix_vlans_datacenter_id', 'vlans', ['datacenter_id'], unique=False)
    op.create_index('ix_vlans_status', 'vlans', ['status'], unique=False)
    op.create_index('ix_vlans_vlan_id', 'vlans', ['vlan_id'], unique=False)
    op.create_table('subnets',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('vlan_id', sa.UUID(), nullable=False),
    sa.Column('network_address', sa.String(length=45), nullable=False),
    sa.Column('cidr', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'network_address', 'cidr', name='uq_subnet_company_network_cidr')
    )
    op.create_index('ix_subnets_company_id', 'subnets', ['company_id'], unique=False)
    op.create_index('ix_subnets_vlan_id', 'subnets', ['vlan_id'], unique=False)
    op.create_table('network_interfaces',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('interface_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('speed_mbps', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_index('ix_net_interfaces_company_id', 'network_interfaces', ['company_id'], unique=False)
    op.create_index('ix_net_interfaces_device_id', 'network_interfaces', ['device_id'], unique=False)
    op.create_index('ix_net_interfaces_interface_type', 'network_interfaces', ['interface_type'], unique=False)
    op.create_index('ix_net_interfaces_mac_address', 'network_interfaces', ['mac_address'], unique=True)
    op.create_index('ix_net_interfaces_status', 'network_interfaces', ['status'], unique=False)
    op.create_table('ip_addresses',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('subnet_id', sa.UUID(), nullable=False),
    sa.Column('device_interface_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.String(length=45), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['device_interface_id'], ['network_interfaces.id'], ),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'address', name='uq_ip_address_company_address')
    )
    op.create_index('ix_ip_addresses_address', 'ip_addresses', ['address'], unique=False)
    op.create_index('ix_ip_addresses_company_id', 'ip_addresses', ['company_id'], unique=False)
    op.create_index('ix_ip_addresses_device_interface_id', 'ip_addresses', ['device_interface_id'], unique=False)
    op.create_index('ix_ip_addresses_status', 'ip_addresses', ['status'], unique=False)
    op.create_index('ix_ip_addresses_subnet_id', 'ip_addresses', ['subnet_id'], unique=False)
    op.create_table('physical_connections',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_interface_id', sa.UUID(), nullable=False),
    sa.Column('destination_interface_id', sa.UUID(), nullable=False),
    sa.Column('connection_type', sa.String(length=20), nullable=False),
    sa.Column('cable_type', sa.String(length=30), nullable=True),
    sa.Column('length_meters', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['destination_interface_id'], ['network_interfaces.id'], ),
    sa.ForeignKeyConstraint(['source_interface_id'], ['network_interfaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_interface_id', 'destination_interface_id', name='uq_connection_interfaces')
    )
    op.create_index('ix_physical_connections_company_id', 'physical_connections', ['company_id'], unique=False)
    op.create_index('ix_physical_connections_destination_interface_id', 'physical_connections', ['destination_interface_id'], unique=False)
    op.create_index('ix_physical_connections_source_interface_id', 'physical_connections', ['source_interface_id'], unique=False)
    op.create_index('ix_physical_connections_status', 'physical_connections', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_physical_connections_status', table_name='physical_connections')
    op.drop_index('ix_physical_connections_source_interface_id', table_name='physical_connections')
    op.drop_index('ix_physical_connections_destination_interface_id', table_name='physical_connections')
    op.drop_index('ix_physical_connections_company_id', table_name='physical_connections')
    op.drop_table('physical_connections')
    op.drop_index('ix_ip_addresses_subnet_id', table_name='ip_addresses')
    op.drop_index('ix_ip_addresses_status', table_name='ip_addresses')
    op.drop_index('ix_ip_addresses_device_interface_id', table_name='ip_addresses')
    op.drop_index('ix_ip_addresses_company_id', table_name='ip_addresses')
    op.drop_index('ix_ip_addresses_address', table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_index('ix_net_interfaces_status', table_name='network_interfaces')
    op.drop_index('ix_net_interfaces_mac_address', table_name='network_interfaces')
    op.drop_index('ix_net_interfaces_interface_type', table_name='network_interfaces')
    op.drop_index('ix_net_interfaces_device_id', table_name='network_interfaces')
    op.drop_index('ix_net_interfaces_company_id', table_name='network_interfaces')
    op.drop_table('network_interfaces')
    op.drop_index('ix_subnets_vlan_id', table_name='subnets')
    op.drop_index('ix_subnets_company_id', table_name='subnets')
    op.drop_table('subnets')
    op.drop_index('ix_vlans_vlan_id', table_name='vlans')
    op.drop_index('ix_vlans_status', table_name='vlans')
    op.drop_index('ix_vlans_datacenter_id', table_name='vlans')
    op.drop_index('ix_vlans_company_id', table_name='vlans')
    op.drop_table('vlans')
    # ### end Alembic commands ###
