"""add ups pdu power_feed tables

Revision ID: 681ac560ac03
Revises: 51af639ebb91
Create Date: 2026-07-22 01:25:58.251602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681ac560ac03'
down_revision: Union[str, Sequence[str], None] = '51af639ebb91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('power_feeds',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('destination_type', sa.String(length=20), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('amp_rating', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'destination_type', 'destination_id', name='uq_power_feed_connection')
    )
    op.create_index('ix_power_feeds_company_id', 'power_feeds', ['company_id'], unique=False)
    op.create_index('ix_power_feeds_destination', 'power_feeds', ['destination_type', 'destination_id'], unique=False)
    op.create_index('ix_power_feeds_source', 'power_feeds', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_power_feeds_status', 'power_feeds', ['status'], unique=False)
    op.create_table('ups_systems',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('capacity_kva', sa.Float(), nullable=False),
    sa.Column('battery_capacity_minutes', sa.Integer(), nullable=True),
    sa.Column('input_voltage', sa.Float(), nullable=True),
    sa.Column('output_voltage', sa.Float(), nullable=True),
    sa.Column('efficiency_percent', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index('ix_ups_company_id', 'ups_systems', ['company_id'], unique=False)
    op.create_index('ix_ups_room_id', 'ups_systems', ['room_id'], unique=False)
    op.create_index('ix_ups_serial_number', 'ups_systems', ['serial_number'], unique=True)
    op.create_index('ix_ups_status', 'ups_systems', ['status'], unique=False)
    op.create_table('pdus',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rack_id', sa.UUID(), nullable=True),
    sa.Column('total_capacity_amp', sa.Float(), nullable=False),
    sa.Column('current_usage_amp', sa.Float(), nullable=False),
    sa.Column('phase_type', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index('ix_pdus_company_id', 'pdus', ['company_id'], unique=False)
    op.create_index('ix_pdus_rack_id', 'pdus', ['rack_id'], unique=False)
    op.create_index('ix_pdus_room_id', 'pdus', ['room_id'], unique=False)
    op.create_index('ix_pdus_serial_number', 'pdus', ['serial_number'], unique=True)
    op.create_index('ix_pdus_status', 'pdus', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pdus_status', table_name='pdus')
    op.drop_index('ix_pdus_serial_number', table_name='pdus')
    op.drop_index('ix_pdus_room_id', table_name='pdus')
    op.drop_index('ix_pdus_rack_id', table_name='pdus')
    op.drop_index('ix_pdus_company_id', table_name='pdus')
    op.drop_table('pdus')
    op.drop_index('ix_ups_status', table_name='ups_systems')
    op.drop_index('ix_ups_serial_number', table_name='ups_systems')
    op.drop_index('ix_ups_room_id', table_name='ups_systems')
    op.drop_index('ix_ups_company_id', table_name='ups_systems')
    op.drop_table('ups_systems')
    op.drop_index('ix_power_feeds_status', table_name='power_feeds')
    op.drop_index('ix_power_feeds_source', table_name='power_feeds')
    op.drop_index('ix_power_feeds_destination', table_name='power_feeds')
    op.drop_index('ix_power_feeds_company_id', table_name='power_feeds')
    op.drop_table('power_feeds')
    # ### end Alembic commands ###
