"""sprint7_add_racks

Revision ID: b59766de5056
Revises: dfe5f7b2470f
Create Date: 2026-07-22 00:39:02.176431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59766de5056'
down_revision: Union[str, Sequence[str], None] = 'dfe5f7b2470f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racks',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('rack_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('height_units', sa.Integer(), nullable=False),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('depth_mm', sa.Float(), nullable=True),
    sa.Column('max_weight_kg', sa.Float(), nullable=True),
    sa.Column('current_weight_kg', sa.Float(), nullable=True),
    sa.Column('power_capacity_kw', sa.Float(), nullable=True),
    sa.Column('current_power_usage_kw', sa.Float(), nullable=True),
    sa.Column('cooling_capacity_kw', sa.Float(), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('position_in_room', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'code', name='uq_rack_room_code'),
    sa.UniqueConstraint('room_id', 'name', name='uq_rack_room_name'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index('ix_racks_company_id', 'racks', ['company_id'], unique=False)
    op.create_index('ix_racks_rack_type', 'racks', ['rack_type'], unique=False)
    op.create_index('ix_racks_room_id', 'racks', ['room_id'], unique=False)
    op.create_index('ix_racks_serial_number', 'racks', ['serial_number'], unique=True)
    op.create_index('ix_racks_status', 'racks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_racks_status', table_name='racks')
    op.drop_index('ix_racks_serial_number', table_name='racks')
    op.drop_index('ix_racks_room_id', table_name='racks')
    op.drop_index('ix_racks_rack_type', table_name='racks')
    op.drop_index('ix_racks_company_id', table_name='racks')
    op.drop_table('racks')
    # ### end Alembic commands ###
