"""sprint5_add_floors

Revision ID: 83f5e5d2b5dd
Revises: 2503d771d871
Create Date: 2026-07-22 00:07:37.877912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f5e5d2b5dd'
down_revision: Union[str, Sequence[str], None] = '2503d771d871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floors',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_area_sqm', sa.Float(), nullable=True),
    sa.Column('max_power_capacity_kw', sa.Float(), nullable=True),
    sa.Column('max_cooling_capacity_kw', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'code', name='uq_floor_building_code'),
    sa.UniqueConstraint('building_id', 'floor_number', name='uq_floor_building_floor_number'),
    sa.UniqueConstraint('building_id', 'name', name='uq_floor_building_name')
    )
    op.create_index('ix_floors_building_id', 'floors', ['building_id'], unique=False)
    op.create_index('ix_floors_company_id', 'floors', ['company_id'], unique=False)
    op.create_index('ix_floors_status', 'floors', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_floors_status', table_name='floors')
    op.drop_index('ix_floors_company_id', table_name='floors')
    op.drop_index('ix_floors_building_id', table_name='floors')
    op.drop_table('floors')
    # ### end Alembic commands ###
