"""add cooling_units environmental_zones sensors tables

Revision ID: c39e59cdb8ff
Revises: 681ac560ac03
Create Date: 2026-07-22 01:45:11.562772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39e59cdb8ff'
down_revision: Union[str, Sequence[str], None] = '681ac560ac03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooling_units',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cooling_capacity_kw', sa.Float(), nullable=False),
    sa.Column('airflow_cfm', sa.Float(), nullable=True),
    sa.Column('power_consumption_kw', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index('ix_cooling_units_company_id', 'cooling_units', ['company_id'], unique=False)
    op.create_index('ix_cooling_units_room_id', 'cooling_units', ['room_id'], unique=False)
    op.create_index('ix_cooling_units_serial_number', 'cooling_units', ['serial_number'], unique=True)
    op.create_index('ix_cooling_units_status', 'cooling_units', ['status'], unique=False)
    op.create_index('ix_cooling_units_type', 'cooling_units', ['type'], unique=False)
    op.create_table('environmental_zones',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_temperature_min', sa.Float(), nullable=True),
    sa.Column('target_temperature_max', sa.Float(), nullable=True),
    sa.Column('target_humidity_min', sa.Float(), nullable=True),
    sa.Column('target_humidity_max', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_env_zones_company_id', 'environmental_zones', ['company_id'], unique=False)
    op.create_index('ix_env_zones_room_id', 'environmental_zones', ['room_id'], unique=False)
    op.create_index('ix_env_zones_status', 'environmental_zones', ['status'], unique=False)
    op.create_table('sensors',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sensor_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location_description', sa.String(length=500), nullable=True),
    sa.Column('last_value', sa.Float(), nullable=True),
    sa.Column('last_unit', sa.String(length=20), nullable=True),
    sa.Column('last_reading_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['environmental_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensors_company_id', 'sensors', ['company_id'], unique=False)
    op.create_index('ix_sensors_sensor_type', 'sensors', ['sensor_type'], unique=False)
    op.create_index('ix_sensors_status', 'sensors', ['status'], unique=False)
    op.create_index('ix_sensors_zone_id', 'sensors', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensors_zone_id', table_name='sensors')
    op.drop_index('ix_sensors_status', table_name='sensors')
    op.drop_index('ix_sensors_sensor_type', table_name='sensors')
    op.drop_index('ix_sensors_company_id', table_name='sensors')
    op.drop_table('sensors')
    op.drop_index('ix_env_zones_status', table_name='environmental_zones')
    op.drop_index('ix_env_zones_room_id', table_name='environmental_zones')
    op.drop_index('ix_env_zones_company_id', table_name='environmental_zones')
    op.drop_table('environmental_zones')
    op.drop_index('ix_cooling_units_type', table_name='cooling_units')
    op.drop_index('ix_cooling_units_status', table_name='cooling_units')
    op.drop_index('ix_cooling_units_serial_number', table_name='cooling_units')
    op.drop_index('ix_cooling_units_room_id', table_name='cooling_units')
    op.drop_index('ix_cooling_units_company_id', table_name='cooling_units')
    op.drop_table('cooling_units')
    # ### end Alembic commands ###
