"""add alerting and incident management tables

Revision ID: cbb5e6a38192
Revises: 2712cd0d42fc
Create Date: 2026-07-22 02:32:33.161993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb5e6a38192'
down_revision: Union[str, Sequence[str], None] = '2712cd0d42fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_key', sa.String(length=255), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('evaluation_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_rules_company_id', 'alert_rules', ['company_id'], unique=False)
    op.create_index('ix_alert_rules_company_metric', 'alert_rules', ['company_id', 'metric_key'], unique=False)
    op.create_index('ix_alert_rules_deleted_at', 'alert_rules', ['deleted_at'], unique=False)
    op.create_index('ix_alert_rules_enabled', 'alert_rules', ['enabled'], unique=False)
    op.create_index('ix_alert_rules_metric_key', 'alert_rules', ['metric_key'], unique=False)
    op.create_index('ix_alert_rules_severity', 'alert_rules', ['severity'], unique=False)
    op.create_table('maintenance_windows',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maintenance_windows_company_id', 'maintenance_windows', ['company_id'], unique=False)
    op.create_index('ix_maintenance_windows_company_status', 'maintenance_windows', ['company_id', 'status'], unique=False)
    op.create_index('ix_maintenance_windows_end_time', 'maintenance_windows', ['end_time'], unique=False)
    op.create_index('ix_maintenance_windows_start_time', 'maintenance_windows', ['start_time'], unique=False)
    op.create_index('ix_maintenance_windows_status', 'maintenance_windows', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_company_device', 'alerts', ['company_id', 'device_id'], unique=False)
    op.create_index('ix_alerts_company_id', 'alerts', ['company_id'], unique=False)
    op.create_index('ix_alerts_company_status', 'alerts', ['company_id', 'status'], unique=False)
    op.create_index('ix_alerts_device_id', 'alerts', ['device_id'], unique=False)
    op.create_index('ix_alerts_open_by_rule', 'alerts', ['rule_id', 'device_id', 'status'], unique=False)
    op.create_index('ix_alerts_rule_id', 'alerts', ['rule_id'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_triggered_at', 'alerts', ['triggered_at'], unique=False)
    op.create_table('incidents',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    op.create_index('ix_incidents_alert_id', 'incidents', ['alert_id'], unique=False)
    op.create_index('ix_incidents_assigned_user_id', 'incidents', ['assigned_user_id'], unique=False)
    op.create_index('ix_incidents_company_id', 'incidents', ['company_id'], unique=False)
    op.create_index('ix_incidents_company_status', 'incidents', ['company_id', 'status'], unique=False)
    op.create_index('ix_incidents_priority', 'incidents', ['priority'], unique=False)
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_priority', table_name='incidents')
    op.drop_index('ix_incidents_company_status', table_name='incidents')
    op.drop_index('ix_incidents_company_id', table_name='incidents')
    op.drop_index('ix_incidents_assigned_user_id', table_name='incidents')
    op.drop_index('ix_incidents_alert_id', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_alerts_triggered_at', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_rule_id', table_name='alerts')
    op.drop_index('ix_alerts_open_by_rule', table_name='alerts')
    op.drop_index('ix_alerts_device_id', table_name='alerts')
    op.drop_index('ix_alerts_company_status', table_name='alerts')
    op.drop_index('ix_alerts_company_id', table_name='alerts')
    op.drop_index('ix_alerts_company_device', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_maintenance_windows_status', table_name='maintenance_windows')
    op.drop_index('ix_maintenance_windows_start_time', table_name='maintenance_windows')
    op.drop_index('ix_maintenance_windows_end_time', table_name='maintenance_windows')
    op.drop_index('ix_maintenance_windows_company_status', table_name='maintenance_windows')
    op.drop_index('ix_maintenance_windows_company_id', table_name='maintenance_windows')
    op.drop_table('maintenance_windows')
    op.drop_index('ix_alert_rules_severity', table_name='alert_rules')
    op.drop_index('ix_alert_rules_metric_key', table_name='alert_rules')
    op.drop_index('ix_alert_rules_enabled', table_name='alert_rules')
    op.drop_index('ix_alert_rules_deleted_at', table_name='alert_rules')
    op.drop_index('ix_alert_rules_company_metric', table_name='alert_rules')
    op.drop_index('ix_alert_rules_company_id', table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
