"""sprint6_add_rooms

Revision ID: dfe5f7b2470f
Revises: 83f5e5d2b5dd
Create Date: 2026-07-22 00:24:40.806486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe5f7b2470f'
down_revision: Union[str, Sequence[str], None] = '83f5e5d2b5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('floor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('room_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('height_meters', sa.Float(), nullable=True),
    sa.Column('max_rack_capacity', sa.Integer(), nullable=True),
    sa.Column('max_power_capacity_kw', sa.Float(), nullable=True),
    sa.Column('max_cooling_capacity_kw', sa.Float(), nullable=True),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('humidity_min', sa.Float(), nullable=True),
    sa.Column('humidity_max', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_id', 'code', name='uq_room_floor_code'),
    sa.UniqueConstraint('floor_id', 'name', name='uq_room_floor_name')
    )
    op.create_index('ix_rooms_company_id', 'rooms', ['company_id'], unique=False)
    op.create_index('ix_rooms_floor_id', 'rooms', ['floor_id'], unique=False)
    op.create_index('ix_rooms_room_type', 'rooms', ['room_type'], unique=False)
    op.create_index('ix_rooms_status', 'rooms', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rooms_status', table_name='rooms')
    op.drop_index('ix_rooms_room_type', table_name='rooms')
    op.drop_index('ix_rooms_floor_id', table_name='rooms')
    op.drop_index('ix_rooms_company_id', table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
